package enum

import (
	"database/sql/driver"

	"github.com/jackc/pgx/pgtype"
)

// GENERATED BY POGO. DO NOT EDIT.

// PostStatus is the "post_status" enum type from "public".
type PostStatus string

const (
	// PostStatusDraft is the 'draft' PostStatus.
	PostStatusDraft = PostStatus("draft")
	// PostStatusPublic is the 'public' PostStatus.
	PostStatusPublic = PostStatus("public")
	// PostStatusPrivate is the 'private' PostStatus.
	PostStatusPrivate = PostStatus("private")
)

// Value satisfies the sql/driver.Valuer interface for PostStatus.
func (postStatus PostStatus) Value() (driver.Value, error) {
	return string(postStatus), nil
}

// EncodeBinary Satisfies the pgtypes.EncodeBinary interface for PostStatus.
func (postStatus PostStatus) EncodeBinary(_ *pgtype.ConnInfo, b []byte) ([]byte, error) {
	return append(b, []byte(postStatus)...), nil
}
